# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='game.proto',
  package='protoblog',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ngame.proto\x12\tprotoblog\"\xe0\x01\n\x0bobservation\x12\r\n\x05\x64\x65\x62ug\x18\x01 \x01(\x05\x1ah\n\x07vehicle\x12\x15\n\rcurrent_speed\x18\x01 \x01(\x05\x12\x18\n\x10\x63urrent_steering\x18\x02 \x01(\x05\x12\x15\n\rcurrent_accel\x18\x03 \x01(\x05\x12\x15\n\rcurrent_brake\x18\x04 \x01(\x05\x1aX\n\x06screen\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x1b\n\x03\x62pp\x18\x03 \x01(\x0e\x32\x0e.protoblog.BPP\x12\x12\n\nimage_data\x18\x04 \x01(\x0c*\x1d\n\x03\x42PP\x12\n\n\x06\x42PP_16\x10\x00\x12\n\n\x06\x42PP_24\x10\x01*D\n\tgameState\x12\x0b\n\x07loading\x10\x00\x12\r\n\tpre_start\x10\x01\x12\x08\n\x04race\x10\x02\x12\x11\n\rrace_finished\x10\x03\x62\x06proto3'
)

_BPP = _descriptor.EnumDescriptor(
  name='BPP',
  full_name='protoblog.BPP',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BPP_16', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BPP_24', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=252,
  serialized_end=281,
)
_sym_db.RegisterEnumDescriptor(_BPP)

BPP = enum_type_wrapper.EnumTypeWrapper(_BPP)
_GAMESTATE = _descriptor.EnumDescriptor(
  name='gameState',
  full_name='protoblog.gameState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='loading', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='pre_start', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='race', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='race_finished', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=283,
  serialized_end=351,
)
_sym_db.RegisterEnumDescriptor(_GAMESTATE)

gameState = enum_type_wrapper.EnumTypeWrapper(_GAMESTATE)
BPP_16 = 0
BPP_24 = 1
loading = 0
pre_start = 1
race = 2
race_finished = 3



_OBSERVATION_VEHICLE = _descriptor.Descriptor(
  name='vehicle',
  full_name='protoblog.observation.vehicle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_speed', full_name='protoblog.observation.vehicle.current_speed', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_steering', full_name='protoblog.observation.vehicle.current_steering', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_accel', full_name='protoblog.observation.vehicle.current_accel', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_brake', full_name='protoblog.observation.vehicle.current_brake', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=160,
)

_OBSERVATION_SCREEN = _descriptor.Descriptor(
  name='screen',
  full_name='protoblog.observation.screen',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='protoblog.observation.screen.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='protoblog.observation.screen.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bpp', full_name='protoblog.observation.screen.bpp', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_data', full_name='protoblog.observation.screen.image_data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=250,
)

_OBSERVATION = _descriptor.Descriptor(
  name='observation',
  full_name='protoblog.observation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='debug', full_name='protoblog.observation.debug', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_OBSERVATION_VEHICLE, _OBSERVATION_SCREEN, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=250,
)

_OBSERVATION_VEHICLE.containing_type = _OBSERVATION
_OBSERVATION_SCREEN.fields_by_name['bpp'].enum_type = _BPP
_OBSERVATION_SCREEN.containing_type = _OBSERVATION
DESCRIPTOR.message_types_by_name['observation'] = _OBSERVATION
DESCRIPTOR.enum_types_by_name['BPP'] = _BPP
DESCRIPTOR.enum_types_by_name['gameState'] = _GAMESTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

observation = _reflection.GeneratedProtocolMessageType('observation', (_message.Message,), {

  'vehicle' : _reflection.GeneratedProtocolMessageType('vehicle', (_message.Message,), {
    'DESCRIPTOR' : _OBSERVATION_VEHICLE,
    '__module__' : 'game_pb2'
    # @@protoc_insertion_point(class_scope:protoblog.observation.vehicle)
    })
  ,

  'screen' : _reflection.GeneratedProtocolMessageType('screen', (_message.Message,), {
    'DESCRIPTOR' : _OBSERVATION_SCREEN,
    '__module__' : 'game_pb2'
    # @@protoc_insertion_point(class_scope:protoblog.observation.screen)
    })
  ,
  'DESCRIPTOR' : _OBSERVATION,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:protoblog.observation)
  })
_sym_db.RegisterMessage(observation)
_sym_db.RegisterMessage(observation.vehicle)
_sym_db.RegisterMessage(observation.screen)


# @@protoc_insertion_point(module_scope)
