# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Py/game.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rPy/game.proto\x12\x02GT\"*\n\x07PosVect\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01z\x18\x03 \x01(\x05\"\x1e\n\tGameState\x12\x11\n\traceState\x18\x01 \x01(\x05\"\x9b\x02\n\x07Vehicle\x12\x10\n\x08\x65ngSpeed\x18\x01 \x01(\x05\x12\x10\n\x08\x65ngBoost\x18\x02 \x01(\x05\x12\x0f\n\x07\x65ngGear\x18\x03 \x01(\x05\x12\r\n\x05speed\x18\x04 \x01(\x05\x12\r\n\x05steer\x18\x05 \x01(\x11\x12\x0b\n\x03pos\x18\x06 \x01(\x05\x12\x11\n\tfLeftSlip\x18\x07 \x01(\x05\x12\x12\n\nfRightSlip\x18\x08 \x01(\x05\x12\x11\n\trLeftSlip\x18\t \x01(\x05\x12\x12\n\nrRightSlip\x18\n \x01(\x05\x12\x0f\n\x07\x65\x43lutch\x18\x0b \x01(\x05\x12\x0f\n\x07\x66LWheel\x18\x0c \x01(\x05\x12\x0f\n\x07\x66RWheel\x18\r \x01(\x05\x12\x0f\n\x07rLWheel\x18\x0e \x01(\x05\x12\x0f\n\x07rRWheel\x18\x0f \x01(\x05\x12\r\n\x05vColl\x18\x10 \x01(\x05\"K\n\x06Screen\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x14\n\x03\x62pp\x18\x04 \x01(\x0e\x32\x07.GT.BPP\"\xcb\x01\n\x0bObservation\x12\x16\n\x02SS\x18\x01 \x01(\x0b\x32\n.GT.Screen\x12\x19\n\x02GS\x18\x02 \x01(\x0b\x32\r.GT.GameState\x12\x17\n\x02VS\x18\x03 \x01(\x0b\x32\x0b.GT.Vehicle\x12\r\n\x05\x66rame\x18\x04 \x01(\x05\x12\x1c\n\x07posVect\x18\x05 \x01(\x0b\x32\x0b.GT.PosVect\x12\x1e\n\tdeltaVect\x18\x06 \x01(\x0b\x32\x0b.GT.PosVect\x12\x0f\n\x07trackID\x18\x07 \x01(\x05\x12\x12\n\ndrivingDir\x18\x08 \x01(\x05*\x1d\n\x03\x42PP\x12\n\n\x06\x42PP_16\x10\x00\x12\n\n\x06\x42PP_24\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Py.game_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BPP']._serialized_start=666
  _globals['_BPP']._serialized_end=695
  _globals['_POSVECT']._serialized_start=21
  _globals['_POSVECT']._serialized_end=63
  _globals['_GAMESTATE']._serialized_start=65
  _globals['_GAMESTATE']._serialized_end=95
  _globals['_VEHICLE']._serialized_start=98
  _globals['_VEHICLE']._serialized_end=381
  _globals['_SCREEN']._serialized_start=383
  _globals['_SCREEN']._serialized_end=458
  _globals['_OBSERVATION']._serialized_start=461
  _globals['_OBSERVATION']._serialized_end=664
# @@protoc_insertion_point(module_scope)
