# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todolist.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='todolist.proto',
  package='protoblog',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0etodolist.proto\x12\tprotoblog\"\xb0\x01\n\x08TodoList\x12\x10\n\x08owner_id\x18\x01 \x01(\x05\x12\x12\n\nowner_name\x18\x02 \x01(\t\x12,\n\x05todos\x18\x03 \x03(\x0b\x32\x1d.protoblog.TodoList.ListItems\x1aP\n\tListItems\x12#\n\x05state\x18\x01 \x01(\x0e\x32\x14.protoblog.TaskState\x12\x0c\n\x04task\x18\x02 \x01(\t\x12\x10\n\x08\x64ue_date\x18\x03 \x01(\t*e\n\tTaskState\x12\r\n\tTASK_OPEN\x10\x00\x12\x14\n\x10TASK_IN_PROGRESS\x10\x01\x12\x13\n\x0fTASK_POST_PONED\x10\x02\x12\x0f\n\x0bTASK_CLOSED\x10\x03\x12\r\n\tTASK_DONE\x10\x04\x62\x06proto3'
)

_TASKSTATE = _descriptor.EnumDescriptor(
  name='TaskState',
  full_name='protoblog.TaskState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TASK_OPEN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TASK_IN_PROGRESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TASK_POST_PONED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TASK_CLOSED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TASK_DONE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=208,
  serialized_end=309,
)
_sym_db.RegisterEnumDescriptor(_TASKSTATE)

TaskState = enum_type_wrapper.EnumTypeWrapper(_TASKSTATE)
TASK_OPEN = 0
TASK_IN_PROGRESS = 1
TASK_POST_PONED = 2
TASK_CLOSED = 3
TASK_DONE = 4



_TODOLIST_LISTITEMS = _descriptor.Descriptor(
  name='ListItems',
  full_name='protoblog.TodoList.ListItems',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='protoblog.TodoList.ListItems.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task', full_name='protoblog.TodoList.ListItems.task', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='due_date', full_name='protoblog.TodoList.ListItems.due_date', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=206,
)

_TODOLIST = _descriptor.Descriptor(
  name='TodoList',
  full_name='protoblog.TodoList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner_id', full_name='protoblog.TodoList.owner_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='owner_name', full_name='protoblog.TodoList.owner_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='todos', full_name='protoblog.TodoList.todos', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TODOLIST_LISTITEMS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=206,
)

_TODOLIST_LISTITEMS.fields_by_name['state'].enum_type = _TASKSTATE
_TODOLIST_LISTITEMS.containing_type = _TODOLIST
_TODOLIST.fields_by_name['todos'].message_type = _TODOLIST_LISTITEMS
DESCRIPTOR.message_types_by_name['TodoList'] = _TODOLIST
DESCRIPTOR.enum_types_by_name['TaskState'] = _TASKSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TodoList = _reflection.GeneratedProtocolMessageType('TodoList', (_message.Message,), {

  'ListItems' : _reflection.GeneratedProtocolMessageType('ListItems', (_message.Message,), {
    'DESCRIPTOR' : _TODOLIST_LISTITEMS,
    '__module__' : 'todolist_pb2'
    # @@protoc_insertion_point(class_scope:protoblog.TodoList.ListItems)
    })
  ,
  'DESCRIPTOR' : _TODOLIST,
  '__module__' : 'todolist_pb2'
  # @@protoc_insertion_point(class_scope:protoblog.TodoList)
  })
_sym_db.RegisterMessage(TodoList)
_sym_db.RegisterMessage(TodoList.ListItems)


# @@protoc_insertion_point(module_scope)
